---
- name: Install ambari-agent
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - ambari-agent

- name: Configure ambari-server hostname in ambari-agent configuration
  lineinfile: 
      dest: /etc/ambari-agent/conf/ambari-agent.ini 
      regexp: '^.*hostname=.*$' 
      line: 'hostname={{ item }}' 
  with_items:
    - "{{ groups.ambari_server[0] }}"

- name: Make sure ambari-agent is running
  service: name=ambari-agent state=started enabled=yes
